feat(01-building-blocks): added workflow file1

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -8,3 +8,12 @@ jobs:
         steps:
             - name: Echo Hello
               run: echo "Hello, World!"
+    echo-goodbye:
+        runs-on: ubuntu-latest
+        steps:
+            - name: Failed step
+              run: |
+                echo "I will fail"  
+                exit 1
+            - name: Echo Goodbye
+              run: echo "Goodbye, World!"
